---

- name: run the SP Keycloak service
  docker_container:
    name: "son-keycloak"
    image: "sonatanfv/son-keycloak:{{ sp_ver }}"
    env:
      KEYCLOAK_USER: "{{ gtk_keycloak_user }}" 
      KEYCLOAK_PASSWORD: "{{ gtk_keycloak_pass }}"
    etc_hosts: >
       {
          "sp.int3.sonata-nfv.eu": "172.20.1.250"
       }
    state: started
    network_mode: bridge
    networks:
      - name: "{{ docker_network_name }}"
        aliases:
          - son-keycloak
    published_ports:
      - "5601:5601"
    restart_policy: "unless-stopped"
