---

- include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ lookup('env','PWD') }}/group_vars/os_{{ pop }}_{{ proj }}_{{ distro }}.yml"
        - "{{ lookup('env','PWD') }}/roles/sp/defaults/main.yml"
      skip: true

- include_vars: "{{ lookup('env','PWD') }}/roles/sp/defaults/main.yml"

- lineinfile:
    dest: "/etc/hosts"
    line: "{{ public_ip }} {{ plat_hostname }}"
    create: yes
    state: present
  become: true

- name: add user 'sonata' with superuser priviledges on Debian machines
  user:
    name: "{{ sp_user }}"
    comment: "SONATA admin user"
    shell: /bin/bash
    group: sudo
    groups: docker
    password: "{{ sp_pass }}"
  when: ansible_os_family == "Debian"

- name: remove password prompt for sudo
  shell: "echo '%sudo ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers"
  when: ansible_os_family == "Debian"

- name: add user 'sonata' with superuser priviledges on CentOS 7 machines
  user:
    name: "{{ sp_user }}"
    comment: "SONATA admin user"
    shell: /bin/bash
    group: wheel
    groups: docker
    password: "{{ sp_pass }}"
  when: ansible_os_family == "RadHat"

- name: remove password prompt for sudo
  shell: "echo 'sonata ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers.d/90-cloud-init-users"
  when: ansible_os_family == "RedHat"

- name: restart docker on Upstart (Ubuntu 14)
  service: name=docker state=restarted
  when: ansible_os_family == "Debian"

- name: restart docker on Systemd (Ubuntu 16 and CentOS 7)
  systemd: name=docker state=restarted daemon_reload=yes
  when: ansible_os_family == "RedHat"


- name: Docker User Defined Network son-sp
  shell: 'if ! [[ "$(docker network inspect {{ docker_network_name }} 2> /dev/null)" == "" ]]; then docker network rm {{ docker_network_name }} ; fi & service docker restart'

- name: Docker creating network
  shell: 'docker network create --driver=bridge --subnet=172.20.1.0/24 --gateway=172.20.1.1 --ip-range=172.20.1.128/25 "{{ docker_network_name }}"'

- name: force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers

# deploy postgreSQL database engine
- include: pgsql.yml

# deploy MongoDB (NoSQL) database engine
- include: mongo.yml

# deploy postgreSQL database engine for monitoring
- include: pgsql-monitoring.yml

# deploy RabbitMQ message bus
- include: broker.yml

# deploy Influxdb
- include: influxdb.yml

# deploy GUI
- include: gui.yml

# deploy BSS
- include: bss.yml

# deploy Gatekepper module
- include: gtk-all.yml

# deploy Repositories
- include: repos.yml

# deploy MANO framework
- include: mano-all.yml

# deploy Infastructure Adaptor
- include: ifta-all.yml

# deploy Monitoring
- include: monit-all.yml

# deploy Security Gateway
- include: sec-gw.yml
