---
- name: deploy a PostgreSQL database server as a Container
  docker_container:
    name: son-monitor-postgres
    image: ntboes/postgres-uuid
    env:
      POSTGRES_DB: "{{ mon_db_name }}"
      POSTGRES_USER: "{{ mon_db_user }}"
      POSTGRES_PASSWORD: "{{ mon_db_pass }}"
    state: started
    command: postgres -p 5433
    network_mode: bridge
    networks:
      - name: "{{ docker_network_name }}"
        aliases:
          - son-monitor-postgres
          - postgsql
    published_ports: 5433:5432
