---

- name: previous install APTitude
  apt: name=aptitude state=present

- name: upgrade all packages to the latest version
  apt: upgrade=yes update_cache=yes

- name: install Python 2.7
  apt: name=python state=present

- name: install useful operating system tools
  apt: name={{ item }} state=latest
  with_items:
  - sysstat
  - nmap
  - tree
  - htop
  - policycoreutils
  - dialog
  - nscd
